import { useState } from 'react'
import { Button, Input, Select } from '@/components/ui'
import { ErrorState, Skeleton, useToast } from '@/components/feedback'
import { AdminDataTable } from '@/features/admin/components/AdminDataTable'
import { ConflictNotice } from '@/features/admin/components/ConflictNotice'
import { DeleteConfirmation } from '@/features/admin/components/DeleteConfirmation'
import { EntityFormDialog } from '@/features/admin/components/EntityFormDialog'
import { createCategory, deleteCategory, updateCategory, type CategoryRequest } from '@/features/admin/adminApi'
import { useAdminCategories, useAdminMutation } from '@/features/admin/adminQueries'
import { ApiError, getSafeErrorMessage } from '@/lib/api/apiError'
import type { Category } from '@/types/domain'

const empty: CategoryRequest = { name: '', slug: '', transactionType: 'BUY' }
export default function CategoryManagementPage() {
  const query = useAdminCategories(); const [editing, setEditing] = useState<Category | null>(); const [deleting, setDeleting] = useState<Category>(); const [form, setForm] = useState(empty); const [conflict, setConflict] = useState(false); const { showToast } = useToast(); const save = useAdminMutation((value: { id?: number; request: CategoryRequest }) => value.id ? updateCategory(value.id, value.request) : createCategory(value.request)); const remove = useAdminMutation(deleteCategory)
  const openCreate = () => { setEditing(null); setForm(empty) }; const openEdit = (item: Category) => { setEditing(item); setForm({ name: item.name, slug: item.slug, transactionType: item.transactionType }) }
  const submit = async () => { if (!form.name.trim() || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug)) return; try { await save.mutateAsync({ id: editing?.id, request: form }); setEditing(undefined); showToast({ type: 'success', title: 'Đã lưu danh mục' }) } catch (error) { if (error instanceof ApiError && error.status === 409) setConflict(true); showToast({ type: 'error', title: 'Không thể lưu danh mục', description: getSafeErrorMessage(error) }) } }
  const columns = [{ key: 'name', header: 'Tên', render: (item: Category) => <strong>{item.name}</strong> }, { key: 'slug', header: 'Slug', render: (item: Category) => item.slug }, { key: 'type', header: 'Giao dịch', render: (item: Category) => item.transactionType === 'BUY' ? 'Mua bán' : 'Cho thuê' }, { key: 'actions', header: 'Thao tác', render: (item: Category) => <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => openEdit(item)}>Sửa</Button><Button size="sm" variant="danger" onClick={() => setDeleting(item)}>Xóa</Button></div> }]
  return <div><div className="flex justify-between gap-4"><div><h2 className="text-3xl font-extrabold">Quản lý danh mục</h2><p className="mt-1 text-ink-600">Cấu hình loại hình mua bán và cho thuê.</p></div><Button onClick={openCreate}>Thêm danh mục</Button></div>{conflict && <div className="mt-5"><ConflictNotice onReload={() => { setConflict(false); query.refetch() }} /></div>}{query.isPending && <Skeleton className="mt-6 h-72" />}{query.isError && <ErrorState onRetry={() => query.refetch()} />}{query.data && <div className="mt-6"><AdminDataTable caption="Danh mục bất động sản" columns={columns} rows={query.data.content} rowKey={(item) => item.id} /></div>}<EntityFormDialog open={editing !== undefined} title={editing ? 'Sửa danh mục' : 'Thêm danh mục'} submitting={save.isPending} onClose={() => setEditing(undefined)} onSubmit={submit}><Input label="Tên danh mục" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><Input label="Slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /><Select label="Loại giao dịch" value={form.transactionType} onChange={(event) => setForm({ ...form, transactionType: event.target.value as CategoryRequest['transactionType'] })}><option value="BUY">Mua bán</option><option value="RENT">Cho thuê</option></Select></EntityFormDialog><DeleteConfirmation open={Boolean(deleting)} name={deleting?.name ?? ''} loading={remove.isPending} onClose={() => setDeleting(undefined)} onConfirm={async () => { if (!deleting) return; try { await remove.mutateAsync(deleting.id); setDeleting(undefined); showToast({ type: 'success', title: 'Đã xóa danh mục' }) } catch (error) { showToast({ type: 'error', title: 'Không thể xóa', description: getSafeErrorMessage(error) }) } }} /></div>
}
