import { useEffect, useRef, useState } from 'react'
import { SlidersHorizontal, X } from 'lucide-react'
import { Button, Input, Select } from '@/components/ui'
import { useCategories } from '@/features/categories/categoryQueries'
import { useDistricts, useProvinces, useWards } from '@/features/locations/locationQueries'
import type { ListingSearchState } from '@/types/domain'

interface Props { value: ListingSearchState; onChange: (updates: Partial<ListingSearchState>) => void }
const optionalNumber = (value: string) => value === '' ? undefined : Number(value)
function Fields({ value, onChange }: Props) {
  const categories = useCategories(); const provinces = useProvinces(); const districts = useDistricts(value.provinceId); const wards = useWards(value.districtId)
  return <div className="grid gap-4"><Input label="Từ khóa" value={value.keyword ?? ''} onChange={(event) => onChange({ keyword: event.target.value || undefined })} placeholder="Quận, dự án, đường…" /><Select label="Nhu cầu" value={value.transactionType ?? ''} onChange={(event) => onChange({ transactionType: (event.target.value || undefined) as ListingSearchState['transactionType'] })}><option value="">Tất cả</option><option value="BUY">Mua bán</option><option value="RENT">Cho thuê</option></Select><Select label="Danh mục" value={value.categoryId ?? ''} onChange={(event) => onChange({ categoryId: optionalNumber(event.target.value) })}><option value="">Tất cả danh mục</option>{categories.data?.content.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Tỉnh / thành phố" value={value.provinceId ?? ''} onChange={(event) => onChange({ provinceId: optionalNumber(event.target.value), districtId: undefined, wardId: undefined })}><option value="">Toàn quốc</option>{provinces.data?.content.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Quận / huyện" disabled={!value.provinceId} value={value.districtId ?? ''} onChange={(event) => onChange({ districtId: optionalNumber(event.target.value), wardId: undefined })}><option value="">Tất cả quận huyện</option>{districts.data?.content.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Phường / xã" disabled={!value.districtId} value={value.wardId ?? ''} onChange={(event) => onChange({ wardId: optionalNumber(event.target.value) })}><option value="">Tất cả phường xã</option>{wards.data?.content.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><div className="grid grid-cols-2 gap-3"><Input label="Giá từ" type="number" min="0" value={value.minPrice ?? ''} onChange={(event) => onChange({ minPrice: optionalNumber(event.target.value) })} /><Input label="Giá đến" type="number" min="0" value={value.maxPrice ?? ''} onChange={(event) => onChange({ maxPrice: optionalNumber(event.target.value) })} /></div><div className="grid grid-cols-2 gap-3"><Input label="Diện tích từ" type="number" min="0" value={value.minArea ?? ''} onChange={(event) => onChange({ minArea: optionalNumber(event.target.value) })} /><Input label="Diện tích đến" type="number" min="0" value={value.maxArea ?? ''} onChange={(event) => onChange({ maxArea: optionalNumber(event.target.value) })} /></div></div>
}
export function ListingFilterPanel(props: Props) { return <aside className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-5 text-lg font-bold">Bộ lọc tìm kiếm</h2><Fields {...props} /></aside> }
export function ListingFilterDrawer(props: Props) {
  const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null); const close = useRef<HTMLButtonElement>(null)
  const dismiss = () => { setOpen(false); trigger.current?.focus() }
  useEffect(() => { if (!open) return; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') dismiss() }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [open])
  return <div className="lg:hidden"><Button ref={trigger} variant="secondary" className="w-full" onClick={() => setOpen(true)}><SlidersHorizontal className="size-4" />Bộ lọc</Button>{open && <div className="fixed inset-0 z-50 bg-slate-950/50" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && dismiss()}><aside role="dialog" aria-modal="true" aria-label="Bộ lọc tìm kiếm" className="ml-auto h-full w-[min(24rem,92vw)] overflow-y-auto bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Bộ lọc</h2><button ref={close} type="button" aria-label="Đóng bộ lọc" onClick={dismiss}><X /></button></div><Fields {...props} /><Button className="mt-6 w-full" onClick={dismiss}>Xem kết quả</Button></aside></div>}</div>
}
