import { Bath, BedDouble, MapPin, Maximize2, Phone } from 'lucide-react'
import { formatAddress, formatArea, formatCurrency } from '@/lib/formatters'
import type { Listing } from '@/types/domain'
import { Button, Card } from '@/components/ui'
import { FavoriteButton } from '@/features/saved-listings/components/FavoriteButton'

export function ListingDetails({ listing }: { listing: Listing }) {
  return <div className="grid gap-6 lg:grid-cols-[1fr_21rem]"><div className="space-y-6"><section><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-2xl font-extrabold text-brand-700">{formatCurrency(listing.price)}</p><FavoriteButton listing={listing} /></div><h1 className="mt-2 text-2xl font-bold text-ink-950 sm:text-3xl">{listing.title}</h1><p className="mt-3 flex items-start gap-2 text-ink-600"><MapPin className="mt-0.5 size-5 shrink-0" aria-hidden="true" />{formatAddress(listing)}</p></section><Card className="grid grid-cols-2 gap-4 p-5 sm:grid-cols-3"><p className="flex items-center gap-2"><Maximize2 className="size-5 text-brand-600" /><span><strong className="block">{formatArea(listing.area)}</strong><small>Diện tích</small></span></p>{listing.bedrooms != null && <p className="flex items-center gap-2"><BedDouble className="size-5 text-brand-600" /><span><strong className="block">{listing.bedrooms}</strong><small>Phòng ngủ</small></span></p>}{listing.bathrooms != null && <p className="flex items-center gap-2"><Bath className="size-5 text-brand-600" /><span><strong className="block">{listing.bathrooms}</strong><small>Phòng tắm</small></span></p>}</Card><section className="rounded-xl bg-white p-6"><h2 className="text-xl font-bold">Mô tả chi tiết</h2><p className="mt-4 whitespace-pre-line leading-7 text-ink-800">{listing.description}</p></section><section className="rounded-xl bg-white p-6"><h2 className="text-xl font-bold">Vị trí và dự án</h2><p className="mt-3 text-ink-600">{formatAddress(listing)}</p>{listing.projectName && <p className="mt-2 font-semibold">Dự án: {listing.projectName}</p>}</section></div><aside className="lg:sticky lg:top-24 lg:self-start"><Card className="p-5"><p className="text-sm text-ink-600">Liên hệ người đăng</p><p className="mt-1 text-lg font-bold">{listing.contactName}</p><a href={`tel:${listing.contactPhone}`}><Button className="mt-5 w-full"><Phone className="size-4" />{listing.contactPhone}</Button></a><p className="mt-3 text-center text-xs text-slate-500">Hãy xác minh thông tin trước khi giao dịch.</p></Card></aside></div>
}
